version: "3.8"
services:
  app:
    container_name: app_petri
    build: ./docker/php
    volumes:
      - ./laravel:/work
    depends_on:
      - db

  web:
    container_name: web_petri
    image: nginx:1.20-alpine
    ports:
      - 8222:80
    volumes:
      - ./laravel:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    container_name: db_petri
    build: ./docker/mysql
    environment:
        MYSQL_ROOT_PASSWORD: petri
        MYSQL_DATABASE: petri
        MYSQL_USER: petri
        MYSQL_PASSWORD: petri
    ports: 
        - 3388:3306        
    command: --default-authentication-plugin=mysql_native_password 
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: